export const LIKE_POST = 'LIKE_POST';
export const SAVE_POST = 'SAVE_POST';
export const DELETE_POST = 'DELETE_POST';
export const EDIT_POST = 'EDIT_POST';
export const SHOW_SNACKBAR = 'SHOW_SNACKBAR';

export const SHOW_POST_LIKES_BAR = 'SHOW_POST_LIKES_BAR';
export const SHOW_COMMENTS_LIKES_BAR = 'SHOW_COMMENTS_LIKES_BAR';
