export enum MEMBER_STATE {
  STATE_NOTHING = 0,
  STATE_ADMIN = 1,
  STATE_TEMP_ADMIN = 2,
  STATE_PENDING = 3,
  STATE_MEMBER = 4,
  STATE_DECLINED = 5,
  STATE_ACCEPT_INVITATION = 6,
  STATE_MEMBER_ACCEPT_INVITATION = 7,
  STATE_INTERESTED_MEMBER = 8,
  STATE_SKIP_PRIVATE_LINK = 9
}
